# Generated by Django 4.2.1 on 2023-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
